app_info:
    name: github.com/godverv/makosh
    version: v0.0.4
    startup_duration: 10s
data_sources: []
server:
    - name: grpc
      port: 80
environment:
    - name: auth_token
      value: auth
      type: string
