name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - "master"

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.6
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry_release:
    runs-on: ubuntu-latest
    needs:
      - tag-release
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1.0.19
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}

  npm-registry-release:
    if: ${{ needs.tag-release.outputs.tag != '' }}
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Release image
        uses: RedSockActions/release_npm_package@v0.0.4
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ needs.tag-release.outputs.tag }}
          WORKING_DIRECTORY: pkg/web/@godverv/makosh